[package]
name = "moser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
confy = "1.0.0"
rand = "0.9.2"
ratatui = "0.29.0"
rodio = "0.21.1"
serde = { version = "1.0.219", features = ["derive"] }
strsim = "0.11.1"
