[project]
name = "moser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pytest>=8.4.1",
    "simpleaudio>=1.0.4",
    "typer>=0.16.1",
]

[tool.basedpyright]
typeCheckingMode = "basic"
